### ISSUE TITLE
ARC stuff

### ISSUE THREAD

**Issue by Yardanico** [Yardanico/random-stuff#1]
Work with arc:
- [x] https://github.com/treeform/typography
- [x] https://github.com/nim-lang/irc - https://github.com/nim-lang/Nim/issues/14207
- [x] https://github.com/bluenote10/NimData
- [x] https://github.com/alehander92/gara
- [x] https://github.com/GULPF/timezones
- [x] https://github.com/bluenote10/NimSvg
- [x] https://github.com/jangko/nimAES
- [x] https://github.com/narimiran/itertools

- [x] https://github.com/jangko/nimpdf

Won't work in arc without changes in the libraries:

https://gist.github.com/Yardanico/5a9f7e9842101443ebf662c58340f406#gistcomment-3289689 :
- [ ] https://github.com/brentp/hts-nim doesn't work https://github.com/nim-lang/Nim/issues/14226 
- [ ] https://github.com/brentp/mosdepth doesn't work because hts-nim doesn't work

A bug or not yet sure:
- [ ] https://github.com/nitely/nim-regex (compiler error in C backend) - https://github.com/nim-lang/Nim/issues/14224
- [ ] nimsuggest - compiles if you put ~10 {.nosinks.}, but fails for the first nimsuggest test.
- [ ] https://github.com/PMunch/nimlsp - doesn't work as it depends on nimsuggest
- [ ] https://github.com/cheatfate/nimcrypto - https://github.com/nim-lang/Nim/issues/14219
- [ ] https://github.com/oprypin/nim-random - https://github.com/nim-lang/Nim/issues/14219

**Comment by Vindaar** [comment]
Just from the top of my head libraries I'm aware of that are broken (I'll update this at a later time):
- persvector: because of `deepCopy` here: 
  https://github.com/PMunch/nim-persistent-vector/blob/master/persvector.nim#L56
- arraymancer: known, issue here: 
  https://github.com/mratsim/Arraymancer/issues/423
- ggplotnim: partly because of the above two, and also because of a similar thing regarding `deepCopy`. I don't know how to replace it.

I've been meaning to check all my libraries anyways. Will do that.

**Comment by Yardanico** [comment]
@Vindaar yeah, thanks for reminding me about deepCopy, https://github.com/NimParsers/parsetoml is also broken because of it

**Comment by Vindaar** [comment]
Ah, related Nim issue regarding `deepCopy`:
https://github.com/nim-lang/Nim/issues/13997

**Comment by Yardanico** [comment]
- [ ] https://github.com/PMunch/combparser - uses a lot of closures which all need nosinks (I think)

**Comment by Yardanico** [comment]
Now tracked in https://github.com/nim-lang/Nim/wiki/Status-of-gc:arc-(library-compatibility)
